/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_mule_api_jni_Bridge */

#ifndef _Included_org_mule_api_jni_Bridge
#define _Included_org_mule_api_jni_Bridge
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     org_mule_api_jni_Bridge
	* Method:    init
	* Signature: ()V
	*/
	JNIEXPORT void JNICALL Java_org_mule_api_jni_Bridge_init
		(JNIEnv *, jobject);

	/*
	* Class:     org_mule_api_jni_Bridge
	* Method:    invokeNetMethod
	* Signature: (Lorg/mule/api/jni/Request;)Lorg/mule/api/jni/Response;
	*/
	JNIEXPORT jobject JNICALL Java_org_mule_api_jni_Bridge_invokeNetMethod
		(JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
